from s224 import *
from s224.alexnet import *
from s224.dense import *
from s28 import *
from s28.alexnet import *
from s28.dense import *
from s32 import *
from s64 import *
from s64.alexnet import *
from s32.alexnet import *
from s64.dense import *
from s32.dense import *